graph LR
    stone[Stone] --> thebuildingbuildingbuilding[The Building Building Building];
    themilitarystrategy[The Military Strategy] --> soldier[Soldier];
    wood[Wood] --> thegrainengine[The Grain Engine];
    clay[Clay] --> theanimalengine[The Animal Engine];
    grain[Grain] --> grainbreed![Grain Breed!];
    grainbreed![Grain Breed!] --> grain[Grain];
    grainbreed![Grain Breed!] --> grain[Grain];
    sheep[Sheep] --> sheepbreed![Sheep Breed!];
    sheepbreed![Sheep Breed!] --> sheep[Sheep];
    sheepbreed![Sheep Breed!] --> sheep[Sheep];
    sheep[Sheep] --> earlysheepclimb![Early Sheep Climb!];
    stone[Stone] --> thestonebuildingbuildingbuilding[The Stone Building Building Building];
    wood[Wood] --> thewoodbuildingbuildingbuilding[The Wood Building Building Building];
    clay[Clay] --> theclaybuildingbuildingbuilding[The Clay Building Building Building];
    thefreesoldier[The Free Soldier] --> soldier[Soldier];
    sheep[Sheep] --> feast![Feast!];
    grain[Grain] --> feast![Feast!];
    feast![Feast!] --> food[Food];
    feast![Feast!] --> food[Food];
    clay[Clay] --> themetagamingcard[The Metagaming Card];
    sheep[Sheep] --> themetagamingcard[The Metagaming Card];
    themilitarybuilding[The Military Building] --> soldier[Soldier];
    themilitarybuilding[The Military Building] --> soldier[Soldier];
    wood[Wood] --> thefood-to-climbenginebuilding[The Food-to-Climb Engine Building];
    cattle[Cattle] --> themilkstrategy[The Milk Strategy];
    wood[Wood] --> timetobuildfences[Time to Build Fences];
    grain[Grain] --> timetobuildfences[Time to Build Fences];
    timetobuildfences[Time to Build Fences] --> sheep[Sheep];
    timetobuildfences[Time to Build Fences] --> cattle[Cattle];
    sheep[Sheep] --> evenmoresheep![Even More Sheep!];
    evenmoresheep![Even More Sheep!] --> sheep[Sheep];
    evenmoresheep![Even More Sheep!] --> sheep[Sheep];
    grain[Grain] --> evenmoregrain![Even More Grain!];
    evenmoregrain![Even More Grain!] --> grain[Grain];
    evenmoregrain![Even More Grain!] --> grain[Grain];
    wood[Wood] --> thecheapbuilding[The Cheap Building];
    wood[Wood] --> thecheapbuilding[The Cheap Building];
    clay[Clay] --> thecombobuilding[The Combo Building];
    wood[Wood] --> thecombobuilding[The Combo Building];
    clay[Clay] --> theredbuilding[The Red Building];
    clay[Clay] --> theredbuilding[The Red Building];
    wood[Wood] --> thecheapstonebuilding[The Cheap Stone Building];
    stone[Stone] --> thecheapstonebuilding[The Cheap Stone Building];
    clay[Clay] --> theredstonebuilding[The Red Stone Building];
    stone[Stone] --> theredstonebuilding[The Red Stone Building];
    stone[Stone] --> thepremiumbuilding[The Premium Building];
    stone[Stone] --> thepremiumbuilding[The Premium Building];
    stone[Stone] --> thefragilebuilding[The Fragile Building];
    glass[Glass] --> thefragilebuilding[The Fragile Building];
    cattle[Cattle] --> cattlebreed![Cattle Breed!];
    cattlebreed![Cattle Breed!] --> cattle[Cattle];
    cattlebreed![Cattle Breed!] --> cattle[Cattle];
    carrot[Carrot] --> veggiesoup[Veggie Soup];
    clay[Clay] --> veggiesoup[Veggie Soup];
    veggiesoup[Veggie Soup] --> food[Food];
    veggiesoup[Veggie Soup] --> food[Food];
    wood[Wood] --> thearmsrace[The Arms Race];
    thearmsrace[The Arms Race] --> soldier[Soldier];
    clay[Clay] --> claysoldier[Clay Soldier];
    claysoldier[Clay Soldier] --> soldier[Soldier];
    stone[Stone] --> themilitarycommitment[The Military Commitment];
    themilitarycommitment[The Military Commitment] --> soldier[Soldier];
    themilitarycommitment[The Military Commitment] --> soldier[Soldier];
    food[Food] --> please,thinkofthechildren[Please, Think of the Children];
    food[Food] --> please,thinkofthechildren[Please, Think of the Children];
    sheep[Sheep] --> sheepclimb![Sheep Climb!];
    grain[Grain] --> grainclimb![Grain Climb!];
    clay[Clay] --> clayclimb![Clay Climb!];
    stone[Stone] --> stoneclimb![Stone Climb!];
    milk[Milk] --> milkclimb![Milk Climb!];
    milk[Milk] --> milkmastery[Milk Mastery];
    wood[Wood] --> thecombothing-in-a-set[The Combo Thing-in-a-Set];
    grain[Grain] --> thecombothing-in-a-set[The Combo Thing-in-a-Set];
    wildboar[Wild Boar] --> theanimalthing-in-a-set[The Animal Thing-in-a-Set];
    cattle[Cattle] --> theanimalthing-in-a-set[The Animal Thing-in-a-Set];
    stone[Stone] --> theexpensivething-in-a-set[The Expensive Thing-in-a-Set];
    silk[Silk] --> theexpensivething-in-a-set[The Expensive Thing-in-a-Set];
    glass[Glass] --> theunfairdeckdive[The Unfair Deck Dive];
    silk[Silk] --> thepayoffgambit[The Payoff Gambit];
    glass[Glass] --> theunexpectedpayoff[The Unexpected Payoff];
    carrot[Carrot] --> theunexpectedpayoff[The Unexpected Payoff];
