name: Build Project

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Install fonts
      run: |
        mkdir ~/.fonts
        cp -r fonts/ ~/.fonts
        fc-cache -f -v
    - name: rake
      run: |
        bundle exec rake
    - name: Upload built cards
      uses: actions/upload-artifact@v1
      with:
        name: cards
        path: _output
